import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();


const user = [
            {
                "id": "TToyRCviAVxSQTp2cY8U",
                "deleted": false,
                "email": "alejandro.coronel@contractorlevelup.com",
                "firstName": "Alejandro",
                "lastName": "Coronel",
                "name": "Alejandro Coronel",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "customMenuLinkReadOnly": false,
                    "customMenuLinkWrite": false,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": false,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/TToyRCviAVxSQTp2cY8U/profile/20b4bb3f-7da4-4913-89cd-c01b584369ec.jpeg",
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-09-06T13:23:33.032Z",
                "dateUpdated": "2024-12-10T14:57:28.892Z"
            },
            {
                "id": "pBPWqp1N73GEyobHRnAi",
                "deleted": false,
                "email": "alejandro.salazar@contractorlevelup.com",
                "firstName": "Alejandro",
                "lastName": "Salazar",
                "name": "Alejandro Salazar",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "customMenuLinkReadOnly": false,
                    "customMenuLinkWrite": false,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": false,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/pBPWqp1N73GEyobHRnAi/profile/950dcfc8-e77d-449e-8b12-fb0f3ca333f7.png",
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-11-22T01:55:32.386Z",
                "dateUpdated": "2024-12-09T22:58:23.577Z"
            },
            {
                "id": "4xzEoHHfJKrkpmQyei9D",
                "deleted": false,
                "email": "sheyla.angarita@contractorlevelup.com",
                "firstName": "Andrea",
                "lastName": "Angarita",
                "name": "Andrea Angarita",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": false,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": false,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": true,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": true,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "customMenuLinkReadOnly": false,
                    "customMenuLinkWrite": false,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": true,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesBulkActionsEnabled": false,
                    "opportunitiesEnabled": false,
                    "paymentsEnabled": true,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": true,
                    "refundsEnabled": false,
                    "reportingEnabled": false,
                    "reviewsEnabled": false,
                    "settingsEnabled": true,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": true,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": true,
                    "workflowsReadOnly": false
                },
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/4xzEoHHfJKrkpmQyei9D/profile/35bad298-6ec0-4799-b833-92d9832fcb9d.png",
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-03-25T23:37:57.315Z",
                "dateUpdated": "2024-12-10T15:15:23.012Z"
            },
            {
                "id": "KuwgM4dJgtvK22Du89wx",
                "deleted": false,
                "email": "angela.valentina@contractorlevelup.com",
                "firstName": "Angela",
                "lastName": "Valentina",
                "name": "Angela Valentina",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": false,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": true,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/KuwgM4dJgtvK22Du89wx/profile/cbc973a0-3225-4f2f-990d-0e191a8ffa13.png",
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-05-23T23:19:00.517Z",
                "dateUpdated": "2024-12-04T22:40:18.679Z"
            },
            {
                "id": "JCXXpfdFpjzEWQNwvFVI",
                "deleted": false,
                "email": "angie.dayana@contractorlevelup.com",
                "firstName": "Angie",
                "lastName": "Arevalo",
                "name": "Angie Arevalo",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": false,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": true,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/JCXXpfdFpjzEWQNwvFVI/profile/04b80074-b1aa-4b73-892d-901dc970b637.jpeg",
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-05-21T00:09:09.849Z",
                "dateUpdated": "2024-12-10T03:00:12.375Z"
            },
            {
                "id": "zKaqng0JyqG21iM0XULU",
                "deleted": false,
                "email": "brandon.marcelo@contractorlevelup.com",
                "firstName": "Brandon",
                "lastName": "Marcelo",
                "name": "Brandon Marcelo",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "customMenuLinkReadOnly": false,
                    "customMenuLinkWrite": false,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesBulkActionsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": false,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-12-04T01:55:58.206Z",
                "dateUpdated": "2024-12-04T23:19:11.629Z"
            },
            {
                "id": "uc4vLppK095cPbjMUIKv",
                "deleted": false,
                "email": "andres.camilo@contractorlevelup.com",
                "firstName": "Camilo",
                "lastName": "Cifuentes",
                "name": "Camilo Cifuentes",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "customMenuLinkReadOnly": false,
                    "customMenuLinkWrite": false,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": false,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "phone": "+13126797421",
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/uc4vLppK095cPbjMUIKv/profile/5b2e8770-c080-47a2-87ef-61ce20fdf14f.jpg",
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-11-22T01:58:27.177Z",
                "dateUpdated": "2024-12-10T03:08:48.100Z"
            },
            {
                "id": "Oq7aj3Nez9igKshNsC9x",
                "deleted": false,
                "email": "carlos.jose@contractorlevelup.com",
                "firstName": "Carlos",
                "lastName": "Jose",
                "name": "Carlos Jose",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "customMenuLinkReadOnly": false,
                    "customMenuLinkWrite": false,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesBulkActionsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": false,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-12-04T01:58:04.337Z",
                "dateUpdated": "2024-12-09T13:24:53.269Z"
            },
            {
                "id": "qd8RwvMHFDemeGTywSe1",
                "deleted": false,
                "email": "carlos.mario@contractorlevelup.com",
                "firstName": "Carlos",
                "lastName": "Mario",
                "name": "Carlos Mario",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": true,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "phone": "+573164897267",
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/qd8RwvMHFDemeGTywSe1/profile/144f4b77-88d4-4da8-9c1d-c268f2b3a38a.jpg",
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-08-30T19:19:21.820Z",
                "dateUpdated": "2024-12-10T04:18:50.654Z"
            },
            {
                "id": "bBzi5kvt4ZpsyEep3tXV",
                "deleted": false,
                "email": "carol.natalia@contractorlevelup.com",
                "firstName": "Carol",
                "lastName": "Natalia",
                "name": "Carol Natalia",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": false,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": true,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/bBzi5kvt4ZpsyEep3tXV/profile/4a163d12-705f-4a30-bf74-7bb67126a24f.png",
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-04-22T21:05:41.609Z",
                "dateUpdated": "2024-12-09T20:44:26.926Z"
            },
            {
                "id": "dp8ooMpFX1DZNX0O2alV",
                "deleted": false,
                "email": "cesar.augusto@contractorlevelup.com",
                "firstName": "Cesar",
                "lastName": "Augusto",
                "name": "Cesar Augusto",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "customMenuLinkReadOnly": false,
                    "customMenuLinkWrite": false,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesBulkActionsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": false,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-12-04T01:59:36.699Z",
                "dateUpdated": "2024-12-04T23:42:14.003Z"
            },
            {
                "id": "cChUBnd1h2YCCQuHcsGC",
                "deleted": false,
                "email": "daniel.santiago@contractorlevelup.com",
                "firstName": "Daniel",
                "lastName": "Avila",
                "name": "Daniel Avila",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": true,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/cChUBnd1h2YCCQuHcsGC/profile/27e4ad48-1a4e-48db-aea1-bae86f003f71.png",
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-09-20T21:58:18.690Z",
                "dateUpdated": "2024-11-23T03:04:20.031Z"
            },
            {
                "id": "GvP4QxwZvFeLQuUvnlic",
                "deleted": false,
                "email": "daniel.fernando@contractorlevelup.com",
                "firstName": "Daniel",
                "lastName": "Fernando",
                "name": "Daniel Fernando",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "customMenuLinkReadOnly": false,
                    "customMenuLinkWrite": false,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesBulkActionsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": false,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-12-04T01:56:54.764Z",
                "dateUpdated": "2024-12-04T14:22:06.503Z"
            },
            {
                "id": "JlIF9i2YxcxWvkWocnv8",
                "deleted": false,
                "email": "john.danilo@contractorlevelup.com",
                "firstName": "Danilo",
                "lastName": "De los Rios",
                "name": "Danilo De los Rios",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": true,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/JlIF9i2YxcxWvkWocnv8/profile/c6628b17-d1ad-4e61-9631-85eb058462b3.JPG",
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-06-14T00:21:02.165Z",
                "dateUpdated": "2024-12-10T02:51:04.765Z"
            },
            {
                "id": "gMZv8i68lG2tUgZtTkEV",
                "deleted": false,
                "email": "david.fernando@contractorlevelup.com",
                "firstName": "David",
                "lastName": "Fernando",
                "name": "David Fernando",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "customMenuLinkReadOnly": false,
                    "customMenuLinkWrite": false,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesBulkActionsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": false,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-12-04T01:59:11.361Z",
                "dateUpdated": "2024-12-04T20:12:21.317Z"
            },
            {
                "id": "4s61QQbVGJUHE5GlyBZF",
                "deleted": false,
                "email": "diana.carolina@contractorlevelup.com",
                "firstName": "Diana",
                "lastName": "Carolina",
                "name": "Diana Carolina",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "customMenuLinkReadOnly": false,
                    "customMenuLinkWrite": false,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesBulkActionsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": false,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-12-04T01:58:27.746Z",
                "dateUpdated": "2024-12-04T17:27:34.745Z"
            },
            {
                "id": "UCFlDU3Qeg8oHan4W4UQ",
                "deleted": false,
                "email": "eduar.aldemar@contractorlevelup.com",
                "firstName": "Eduard",
                "lastName": "Aldemar",
                "name": "Eduard Aldemar",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": true,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/UCFlDU3Qeg8oHan4W4UQ/profile/fc5c2ad1-4f3d-4f69-8ab6-119bb724d8c2.png",
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-09-20T22:00:23.568Z",
                "dateUpdated": "2024-12-10T15:10:15.258Z"
            },
            {
                "id": "6MKRJPXoW9aXiePMM6Mr",
                "deleted": false,
                "email": "fabricio.sitto@contractorlevelup.com",
                "firstName": "Fabricio",
                "lastName": "Sitto",
                "name": "Fabricio Sitto",
                "permissions": {
                    "adPublishingEnabled": true,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": true,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": true,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": false,
                    "attributionsReportingEnabled": true,
                    "bloggingEnabled": true,
                    "botService": false,
                    "bulkRequestsEnabled": true,
                    "campaignsEnabled": true,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": true,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "customMenuLinkReadOnly": false,
                    "customMenuLinkWrite": false,
                    "dashboardStatsEnabled": true,
                    "exportPaymentsEnabled": true,
                    "facebookAdsReportingEnabled": true,
                    "funnelsEnabled": true,
                    "invoiceEnabled": true,
                    "leadValueEnabled": true,
                    "marketingEnabled": true,
                    "mediaStorageEnabled": true,
                    "membershipEnabled": true,
                    "onlineListingsEnabled": true,
                    "opportunitiesBulkActionsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": true,
                    "phoneCallEnabled": true,
                    "recordPaymentEnabled": true,
                    "refundsEnabled": true,
                    "reportingEnabled": true,
                    "reviewsEnabled": true,
                    "settingsEnabled": true,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": true,
                    "websitesEnabled": true,
                    "wordpressEnabled": false,
                    "workflowsEnabled": true,
                    "workflowsReadOnly": false
                },
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/6MKRJPXoW9aXiePMM6Mr/profile/44757115-eec1-4612-9144-51d456e70d96.png",
                "roles": {
                    "type": "agency",
                    "role": "admin",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-01-17T15:40:23.140Z",
                "dateUpdated": "2024-12-10T15:13:56.033Z"
            },
            {
                "id": "1kMZCtDGbsMe9ye8PEUN",
                "deleted": false,
                "email": "franco.delavega@contractorlevelup.com",
                "firstName": "Franco",
                "lastName": "De La Vega",
                "name": "Franco De La Vega",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": false,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": true,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": false,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "customMenuLinkReadOnly": false,
                    "customMenuLinkWrite": false,
                    "dashboardStatsEnabled": true,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": true,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesBulkActionsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": true,
                    "phoneCallEnabled": true,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": true,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": true,
                    "workflowsReadOnly": false
                },
                "phone": "",
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/1kMZCtDGbsMe9ye8PEUN/profile/85366cbc-5571-4afe-a812-e10a4f387c9c.jpg",
                "roles": {
                    "type": "account",
                    "role": "admin",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-04-15T23:53:51.405Z",
                "dateUpdated": "2024-12-10T14:34:39.257Z"
            },
            {
                "id": "G7TdWu29wi8TGepLJUb8",
                "deleted": false,
                "email": "gabriela.luna@contractorlevelup.com",
                "extension": "",
                "firstName": "Gabriela",
                "lastName": "Luna",
                "name": "Gabriela Luna",
                "permissions": {
                    "adwordsReportingEnabled": true,
                    "affiliateManagerEnabled": true,
                    "agentReportingEnabled": true,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": false,
                    "attributionsReportingEnabled": true,
                    "bloggingEnabled": true,
                    "botService": false,
                    "bulkRequestsEnabled": true,
                    "campaignsEnabled": true,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": true,
                    "contactsEnabled": true,
                    "contentAiEnabled": true,
                    "conversationsEnabled": true,
                    "dashboardStatsEnabled": true,
                    "facebookAdsReportingEnabled": true,
                    "funnelsEnabled": true,
                    "invoiceEnabled": true,
                    "leadValueEnabled": true,
                    "marketingEnabled": true,
                    "membershipEnabled": true,
                    "onlineListingsEnabled": true,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": true,
                    "phoneCallEnabled": true,
                    "recordPaymentEnabled": true,
                    "refundsEnabled": true,
                    "reviewsEnabled": true,
                    "settingsEnabled": true,
                    "socialPlanner": true,
                    "tagsEnabled": true,
                    "triggersEnabled": true,
                    "websitesEnabled": true,
                    "workflowsEnabled": true,
                    "workflowsReadOnly": false
                },
                "phone": "",
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/G7TdWu29wi8TGepLJUb8/profile/37a393e5-4513-4f1b-a694-a8323b0c8b4a.png",
                "roles": {
                    "type": "agency",
                    "role": "admin",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2023-07-09T01:16:26.316Z",
                "dateUpdated": "2024-12-09T01:54:52.623Z"
            },
            {
                "id": "a81ooVnIEPy1yea5HmIX",
                "deleted": false,
                "email": "helena.maria@contractorlevelup.com",
                "firstName": "Helena",
                "lastName": "Maria",
                "name": "Helena Maria",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": true,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/a81ooVnIEPy1yea5HmIX/profile/117ffd8c-b525-425e-8754-e01935ede35e.jpeg",
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-08-30T19:21:34.933Z",
                "dateUpdated": "2024-12-10T14:46:57.014Z"
            },
            {
                "id": "GwFKMjgpNjgd9YALqKhb",
                "deleted": false,
                "email": "isabella.echeverria@contractorlevelup.com",
                "firstName": "Isabella",
                "lastName": "Echeverria",
                "name": "Isabella Echeverria",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": false,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": true,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": true,
                    "opportunitiesEnabled": false,
                    "paymentsEnabled": true,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": true,
                    "reviewsEnabled": true,
                    "settingsEnabled": true,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": true
                },
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/GwFKMjgpNjgd9YALqKhb/profile/34b81cd5-d5ad-4d5b-ad3e-65521f177ff1.jpg",
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-10-11T22:30:26.458Z",
                "dateUpdated": "2024-12-10T13:37:14.034Z"
            },
            {
                "id": "tjDrd07nO7rXkhNYnb7G",
                "deleted": false,
                "email": "wilson.ivan@contractorlevelup.com",
                "firstName": "Ivan",
                "lastName": "Mosquera",
                "name": "Ivan Mosquera",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": true,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": true,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/tjDrd07nO7rXkhNYnb7G/profile/1be19ad3-e126-4f22-8cac-b6155fa99e27.png",
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-09-20T22:00:44.068Z",
                "dateUpdated": "2024-12-10T03:13:05.592Z"
            },
            {
                "id": "E52nMuZeVK9eusnPNboD",
                "deleted": false,
                "email": "ivana.fiorella@contractorlevelup.com",
                "firstName": "Ivana",
                "lastName": "Fiorella",
                "name": "Ivana Fiorella",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": false,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": true,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/E52nMuZeVK9eusnPNboD/profile/00d6fc0a-b582-44c2-a252-a820c0882479.jpg",
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-05-23T23:17:07.069Z",
                "dateUpdated": "2024-12-10T15:15:53.460Z"
            },
            {
                "id": "YFjvKskhUrORFxRpIY9C",
                "deleted": false,
                "email": "javier.romero@contractorlevelup.com",
                "firstName": "Javier ",
                "lastName": "Romero",
                "name": "Javier  Romero",
                "permissions": {
                    "adPublishingEnabled": false,
                    "adPublishingReadOnly": false,
                    "adwordsReportingEnabled": false,
                    "affiliateManagerEnabled": false,
                    "agentReportingEnabled": false,
                    "appointmentsEnabled": true,
                    "assignedDataOnly": true,
                    "attributionsReportingEnabled": false,
                    "bloggingEnabled": false,
                    "botService": false,
                    "bulkRequestsEnabled": false,
                    "campaignsEnabled": false,
                    "campaignsReadOnly": false,
                    "cancelSubscriptionEnabled": false,
                    "certificatesEnabled": false,
                    "communitiesEnabled": false,
                    "contactsEnabled": true,
                    "contentAiEnabled": false,
                    "conversationsEnabled": true,
                    "dashboardStatsEnabled": false,
                    "exportPaymentsEnabled": false,
                    "facebookAdsReportingEnabled": false,
                    "funnelsEnabled": false,
                    "invoiceEnabled": false,
                    "leadValueEnabled": false,
                    "marketingEnabled": false,
                    "mediaStorageEnabled": false,
                    "membershipEnabled": false,
                    "onlineListingsEnabled": false,
                    "opportunitiesEnabled": true,
                    "paymentsEnabled": false,
                    "phoneCallEnabled": false,
                    "recordPaymentEnabled": false,
                    "refundsEnabled": false,
                    "reportingEnabled": true,
                    "reviewsEnabled": false,
                    "settingsEnabled": false,
                    "socialPlanner": false,
                    "tagsEnabled": true,
                    "triggersEnabled": false,
                    "websitesEnabled": false,
                    "wordpressEnabled": false,
                    "workflowsEnabled": false,
                    "workflowsReadOnly": false
                },
                "profilePhoto": "https://msgsndr-private.storage.googleapis.com/user/YFjvKskhUrORFxRpIY9C/profile/6b84e45b-93fd-4d12-9945-288858e650a1.jpg",
                "roles": {
                    "type": "account",
                    "role": "user",
                    "locationIds": [
                        "7gcRvmSzndyAWZHzYU01"
                    ],
                    "restrictSubAccount": false
                },
                "dateAdded": "2024-04-16T00:25:05.523Z",
                "dateUpdated": "2024-12-10T02:38:47.647Z"
            }
        ]
async function main() {
  const dataToInsert = user.map((user) => ({
    idUser_High_Level: user.id,
    full_name: user.name,
    first_name: user.firstName,
    last_name: user.lastName,
    email: user.email,
    password: "ea6eb6f8e7b3535a169e6fd895a59695",
    status: true,
    is_admin: false,
    messages_minute: 100,
  }));

  for (const userData of dataToInsert) {
    try {
      const existingUser = await prisma.user.findUnique({
        where: { email: userData.email },
      });

      if (!existingUser) {
        await prisma.user.create({ data: userData });
        console.log(`User with email ${userData.email} added!`);
      } else {
        console.log(`User with email ${userData.email} already exists.`);
      }
    } catch (error) {
      console.error(`Error processing user with email ${userData.email}:`, error);
    }
  }
}

main()
  .catch((e) => console.error("Unexpected error:", e))
  .finally(async () => {
    await prisma.$disconnect();
  });